### ISSUE TITLE
Move language-specific documentation to track repositories

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#1]
Goal: https://github.com/exercism/rossconf/issues/11

Nobody should have to deal with documentation for languages they're not maintaining, and all maintainers should be able to accept pull requests to the documentation that is relevant to them.

---------

**Skillset:** This is a great task for someone who is completely new to programming, as the technical requirement is that you can read.

You will be making decisions about how to split up and categorise instructions, and as you go through this you will be in a unique position to find places where the instructions are confusing or lacking. In this case, if you see how to improve it: go for it! Otherwise, open an issue in the language-specific repository with a description of what's confusing.

---------

We've solved this problem when it comes to maintaining the actual exercises in different languages: Each language track lives in its own repository. This is very handy. It means that someone who helps maintain the Haskell language track, only needs to worry about cloning the [exercism/xhaskell](https://github.com/exercism/xhaskell) repository. No need to install Ruby, no need to worry about problems for 20 or so other languages.

Then the [x-api repository](https://github.com/exercism/x-api/tree/master/problems), which is the thing that serves up exercises in all the languages when you say `exercism fetch`, links to all the different language-specific repositories.

Instead of putting all the documentation in one place, we can put language-specific documentation in each language-specific repository. That means that the people who are maintaining that language track can easily maintain their relevant documentation without having to deal with other repositories, and also that the Problem API can serve up documentation about how to get started in a language.

That in turn will let us do a few things, for example, we could give you the getting started documentation on the command-line:

```
exercism help ruby
```

Or we could deliver a [track-level README](https://github.com/exercism/x-api/issues/31) that is based on this content.

Also, we can have a language-specific landing page on the website that would include the getting started documentation and resources (see issue https://github.com/exercism/exercism.io/issues/2299).

------------

**TODO**

Pick a repository from the list below, and add a comment to this issue saying "dibs" and the language, so that nobody is duplicating effort.

- clone the repository
- create a `docs/` directory
- edit the `config.json` file and add "docs" to the `ignored` key, so that the Travis CI build doesn't fail.
- find the correct language documentation file here: https://github.com/exercism/docs/tree/master/app/pages/languages
- click to go to the file, and click on the "raw" button above the file to get raw text.
- copy the text into blank files in the `docs/` directory.

There might be only a couple sections, or there could be more. We need to standardize the names so that the `x-api` can find the documentation and serve it consistently.

- `INSTALLATION.md` - should contain details about installing the language itself and any dependencies or configuration necessary to work on the exercises in that language.
- `WORKFLOW.md` - should contain details about how to run the test suite for each exercise (described generically). Sometimes this will just be a single command, sometimes it will be more involved with instructions about a build system or how to do it via an IDE.
- `HELLO.md` - sometimes there's some content about how to write your first module or class or program in that language.
- `TOOLS.md` - if there's anything about using automated tools for formatting, linting, warnings, etc, it can go into 
- `RESOURCES.md` - links to useful resources on the web or elsewhere.

If you find sections that don't match these things, post back here and we can make up a new standardized category for it.

------------

**Resources**

There's a bunch of detail about the problem API and how each of the language tracks are organized in order to make it possible to serve up the problems in the CONTRIBUTING guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

In particular, you might want to take a look at what the `config.json` file is for: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#configjson

Also, read about the `configlet` tool: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#configlet

------------

Here's the list of repositories:

- [x] https://github.com/exercism/xclojure
- [x] https://github.com/exercism/xcoffeescript
- [x] https://github.com/exercism/xcpp
- [x] https://github.com/exercism/xcsharp
- [x] https://github.com/exercism/xelixir
- [x] https://github.com/exercism/xerlang
- [x] https://github.com/exercism/xfsharp
- [x] https://github.com/exercism/xgo
- [x] https://github.com/exercism/xhaskell
- [x] https://github.com/exercism/xjava
- [ ] https://github.com/exercism/xjavascript
- [ ] https://github.com/exercism/xlisp
- [ ] https://github.com/exercism/xlua
- [ ] https://github.com/exercism/xobjective-c
- [ ] https://github.com/exercism/xocaml
- [ ] https://github.com/exercism/xperl5
- [x] https://github.com/exercism/xphp
- [ ] https://github.com/exercism/xplsql
- [x] https://github.com/exercism/xpython
- [x] https://github.com/exercism/xruby
- [x] https://github.com/exercism/xscala
- [ ] https://github.com/exercism/xscheme
- [x] https://github.com/exercism/xswift

---------

**NOTE** When creating a pull request, please refer to the original issue: https://github.com/exercism/x-common/issues/69

**Comment by studiolo** [comment]
Hi, if there is strong competition for https://github.com/exercism/rossconf/issues/10 I'd be happy to work on this.

**Comment by vguerra** [comment]
dibs ruby
I'll start migrating the docs for the ruby repo since we are at a ruby hackaton =)

**Comment by kytrinyx** [comment]
:)

**Comment by vguerra** [comment]
I have seen that all getting-started-xxxx.md files start w/some metadata. What about having as well a separate md file for it? I would put that metadata into a separate file: METADATA.md for instance.  I imagine that this metadata is useful for some other documentation processing right? =)

**Comment by vguerra** [comment]
dibs haskell

**Comment by kytrinyx** [comment]
I'm not sure about the metadata. If we do, it should probably be `json` or `yml`, but I think that this can be inferred from the repo that it is in (language name, for example, is in the repo's `config.json`).

**Comment by vguerra** [comment]
yes.. that info can be inferred from the repository itself, but what about the ordinal? ... maybe it could be an extra value pair in the config.json file?

**Comment by kytrinyx** [comment]
We won't be using the ordinal anymore, that was a hack because I couldn't figure out how to order things alphabetically :)

**Comment by vguerra** [comment]
great.. then i'll leave the metadata out =)

**Comment by vguerra** [comment]
dibs swift.

**Comment by vguerra** [comment]
dibs clojure
dibs coffeescript

**Comment by vguerra** [comment]
dibs xcpp

**Comment by vguerra** [comment]
dibs go
