### ISSUE TITLE
Initial "Hello World" exercise in each language track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/todo#2]
See goal: https://github.com/exercism/rossconf/issues/12

---------

**Skillset:** If you know any single language that we have a track for on exercism, you can help! You will need to figure out how to write a small test suite in that language, as well as a small code example that passes the test suite, and some helpful guidance on getting started (suggestions for this exist).

---------

**TODO**

Pick a repository from the list below, and add a comment to this issue saying "dibs" and the language, so that nobody is duplicating effort.

1. Create a new directory named `hello-world`. In the directory, add:
  - A test suite using the naming conventions of that language track
  - A `HELLO.md` file with the getting started instructions (see https://github.com/exercism/exercism.io/issues/2021#issuecomment-93412385 for inspiration)
  - An example solution that solves the test suite
2. Edit `config.json`, adding  `hello-world` as the the first entry in the list of problems.

Here's the relevant part of the CONTRIBUTING guide for adding a brand new problem:
https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#submitting-new-problems

**NOTE** When submitting a pull request, please refer to the original issue: https://github.com/exercism/exercism.io/issues/2021

-----------

Here's the list of language repositories:

- [ ] https://github.com/exercism/xclojure
- [x] https://github.com/exercism/xcoffeescript
- [ ] https://github.com/exercism/xcpp
- [ ] https://github.com/exercism/xcsharp
- [ ] https://github.com/exercism/xelixir
- [ ] https://github.com/exercism/xerlang
- [ ] https://github.com/exercism/xfsharp
- [ ] https://github.com/exercism/xgo
- [ ] https://github.com/exercism/xhaskell
- [ ] https://github.com/exercism/xjava
- [x] https://github.com/exercism/xjavascript
- [ ] https://github.com/exercism/xlisp
- [x] https://github.com/exercism/xlua
- [x] https://github.com/exercism/xobjective-c
- [ ] https://github.com/exercism/xocaml
- [ ] https://github.com/exercism/xperl5
- [ ] https://github.com/exercism/xphp
- [ ] https://github.com/exercism/xplsql
- [x] https://github.com/exercism/xpython
- [x] https://github.com/exercism/xruby
- [x] https://github.com/exercism/xscala
- [x] https://github.com/exercism/xscheme
- [x] https://github.com/exercism/xswift

**Comment by ramonh** [comment]
Heya! I'll go ahead and give the ruby hello-world exercise a go.

**Comment by michaelem** [comment]
I'm doing the python one now :)

**Comment by ramonh** [comment]
I'll go ahead and do the CoffeeScript one now!

**Comment by ramonh** [comment]
I'm on the Objective-C one now!

**Comment by trayo** [comment]
I'm giving the Javascript one a shot!

**Comment by trayo** [comment]
Dibs on Lua!

**Comment by kytrinyx** [comment]
I'm closing this issue in favor of individual issues for each track--it's easier to maintain. See https://github.com/exercism/todo/labels/hello-world

Thanks, everyone!
